import assert from 'node:assert/strict'
import test from 'node:test'
import { layoutBackground } from '../../src/preview/engine/background'
import {
    createViewport,
    defaultCameraInfo,
    getCameraInfo,
    type CameraChange,
} from '../../src/preview/engine/layout'
import { EaseType } from '../../src/preview/engine/math'

const camera = (overrides: Partial<CameraChange> = {}): CameraChange => ({
    time: 0,
    lane: 0,
    size: 6,
    zoom: 1,
    zoomTargetLane: 0,
    zoomTargetY: 0,
    zoomVerticalAlign: 0,
    rotate: 0,
    stageTilt: 1,
    ease: EaseType.linear,
    ...overrides,
})

const close = (actual: number, expected: number) =>
    assert.ok(Math.abs(actual - expected) < 1e-10, `${actual} != ${expected}`)

test('charts without cameras keep the original background cover fit in every aspect', () => {
    for (const [width, height, halfWidth, halfHeight] of [
        [1600, 900, 16 / 9, 1],
        [2100, 900, 21 / 9, 21 / 16],
        [1200, 900, 16 / 9, 1],
    ] as const) {
        const quad = layoutBackground(createViewport(width, height), [], defaultCameraInfo())
        close(quad.bl.x, -halfWidth)
        close(quad.bl.y, -halfHeight)
        close(quad.tl.x, -halfWidth)
        close(quad.tl.y, halfHeight)
        close(quad.tr.x, halfWidth)
        close(quad.tr.y, halfHeight)
        close(quad.br.x, halfWidth)
        close(quad.br.y, -halfHeight)
    }
})

// Generated by calling background_camera_zoom and apply_camera_zoom in engine
// 9e93ba0, sekai/lib/layout.py, with a cover-fitted 16:9 image and default options.
// Includes neutral-camera overscan, off-center targets, both anchors, three
// aspect ratios, flat/partial/full tilt, reversed and >90-degree rotations.
const engineCases = [
    {
        aspect: 16 / 9,
        camera: camera({ stageTilt: 0 }),
        corners: [
            [-2.1230978343095765, -1.1942425317991368],
            [-2.1230978343095765, 1.1942425317991368],
            [2.1230978343095765, 1.1942425317991368],
            [2.1230978343095765, -1.1942425317991368],
        ],
    },
    {
        aspect: 16 / 9,
        camera: camera({
            rotate: 0.4,
            zoom: 1.3,
            stageTilt: 0.5,
            lane: 1.5,
            size: 4,
            zoomTargetLane: -0.75,
            zoomTargetY: 0.35,
        }),
        corners: [
            [-4.601563948172114, -1.4209550223968535],
            [-2.7713883637279726, 2.9078173025386116],
            [4.924206880601742, -0.3458281809176391],
            [3.094031296157601, -4.674600505853104],
        ],
    },
    {
        aspect: 21 / 9,
        camera: camera({
            rotate: -0.7,
            zoom: 0.8,
            stageTilt: 0,
            zoomTargetY: 0.5,
            zoomVerticalAlign: 1,
        }),
        corners: [
            [-1.309293117203333, -3.8814167377075397],
            [-3.8472627271384523, -0.8682330481263347],
            [1.5095082765614667, 3.643712925091654],
            [4.047477886496585, 0.630529235510449],
        ],
    },
    {
        aspect: 4 / 3,
        camera: camera({ rotate: 2.2, zoom: 1.5, lane: -1, size: 5, zoomTargetLane: 1 }),
        corners: [
            [1.0081250704668565, 5.633247362456784],
            [5.40395696352874, 2.433539895469882],
            [-0.28441186667019647, -5.381272358862353],
            [-4.68024375973208, -2.1815648918754516],
        ],
    },
    {
        aspect: 4 / 3,
        camera: camera({
            rotate: -0.03,
            zoom: 1.1,
            stageTilt: 0.02,
            lane: 2,
            size: 3,
            zoomTargetLane: 0.5,
            zoomTargetY: 0.7,
            zoomVerticalAlign: 1,
        }),
        corners: [
            [-2.0078382756328335, -1.7859632190631238],
            [-2.086051453993415, 0.8203605475740573],
            [2.54741302002824, 0.9594061979928689],
            [2.625626198388822, -1.6469175686443123],
        ],
    },
]

test('background corners match the game engine reference', () => {
    for (const fixture of engineCases) {
        const viewport = createViewport(fixture.aspect * 900, 900)
        const cameras = [fixture.camera]
        const quad = layoutBackground(viewport, cameras, getCameraInfo(viewport, cameras, 0))
        for (const [index, corner] of (['bl', 'tl', 'tr', 'br'] as const).entries()) {
            close(quad[corner].x, fixture.corners[index]![0]!)
            close(quad[corner].y, fixture.corners[index]![1]!)
        }
    }
})

test('rotation overscan accounts for the whole chart and stays fixed while seeking', () => {
    const viewport = createViewport(1600, 900)
    const cameras = [camera(), camera({ time: 10, rotate: -Math.PI })]
    const at = (time: number) =>
        layoutBackground(viewport, cameras, getCameraInfo(viewport, cameras, time))
    const first = at(-1)
    const width = (quad: ReturnType<typeof at>) =>
        Math.hypot(quad.tr.x - quad.tl.x, quad.tr.y - quad.tl.y)
    assert.ok(width(first) > width(layoutBackground(viewport, [camera()], defaultCameraInfo())))
    for (const time of [0, 2.5, 5, 7.5, 10, 20, -1]) close(width(at(time)), width(first))
    assert.deepEqual(at(-1), first)

    // A camera edit supplies a new compiled array and must invalidate overscan.
    const edited = [camera(), camera({ time: 10, rotate: 0.1 })]
    assert.ok(
        width(layoutBackground(viewport, edited, getCameraInfo(viewport, edited, 0))) <
            width(first),
    )
})

test('camera lane and size do not independently pan or stretch the background', () => {
    const viewport = createViewport(1600, 900)
    const cameras = [camera()]
    const base = getCameraInfo(viewport, cameras, 0)
    assert.deepEqual(
        layoutBackground(viewport, cameras, { ...base, lane: 5, size: 2, stageTilt: 0 }),
        layoutBackground(viewport, cameras, base),
    )
})
