import assert from 'node:assert/strict'
import { test } from 'node:test'
import {
    createTimescaleGroup,
    hideNotesAt,
    noteDistance,
    scaledTimeAt,
    type TimescaleChange,
    type TimescaleEase,
} from '../../src/preview/engine/timescale.ts'

const change = (
    time: number,
    timescale: number,
    properties: Partial<TimescaleChange> = {},
): TimescaleChange => ({
    time,
    timescale,
    skipSeconds: 0,
    ease: 0,
    transitionStyle: 0,
    hideNotes: false,
    ...properties,
})

const close = (actual: number, expected: number) => {
    assert.ok(
        Math.abs(actual - expected) <= 1e-10 * Math.max(1, Math.abs(expected)),
        `Expected ${actual} to be close to ${expected}`,
    )
}

test('integrates all six easing modes, including both halves of piecewise quadratic curves', () => {
    const firstSecond = [1, 1.5, 13 / 12, 23 / 12, 7 / 6, 11 / 6]
    const fullInterval = [4, 12, 28 / 3, 44 / 3, 12, 12]
    for (let ease = 0; ease <= 5; ease++) {
        const rising = createTimescaleGroup(
            [change(0, 1, { ease: ease as TimescaleEase }), change(4, 5)],
            0,
        )
        const falling = createTimescaleGroup(
            [change(0, 5, { ease: ease as TimescaleEase }), change(4, 1)],
            0,
        )
        close(scaledTimeAt(rising, 1), firstSecond[ease]!)
        close(noteDistance(rising, 0, 4), fullInterval[ease]!)
        close(noteDistance(rising, 4, 0), -fullInterval[ease]!)
        close(noteDistance(falling, 0, 1), 6 - firstSecond[ease]!)
        close(noteDistance(falling, 0, 4), 24 - fullInterval[ease]!)
        close(noteDistance(rising, 1, 3), noteDistance(rising, 1, 2) + noteDistance(rising, 2, 3))
    }
})

test('scroll uses current eased speed for both future and past targets', () => {
    const quarterSpeeds = [1, 2, 1.25, 2.75, 1.5, 2.5]
    for (let ease = 0; ease <= 5; ease++) {
        const group = createTimescaleGroup(
            [change(0, 1, { ease: ease as TimescaleEase, transitionStyle: 1 }), change(4, 5)],
            0,
        )
        close(noteDistance(group, 1, 3), quarterSpeeds[ease]! * 2)
        close(noteDistance(group, 1, 0), -quarterSpeeds[ease]!)
    }
})

test('mixed style, tied marker, skip, zero speed and reverse queries match the engine reference', () => {
    const group = createTimescaleGroup(
        [
            change(-4, 2, { ease: 2, transitionStyle: 1, skipSeconds: 0.5 }),
            change(-1, -0.5, { ease: 5, transitionStyle: 1, skipSeconds: -0.25 }),
            change(0, 3, { skipSeconds: 1 }),
            change(0, 0.25, { ease: 4, transitionStyle: 1, skipSeconds: -0.5 }),
            change(2, 0, { ease: 3, transitionStyle: 1, skipSeconds: 0.1 }),
            change(3, -2, { ease: 1, skipSeconds: -0.75 }),
            change(5, 1.5, { ease: 2, skipSeconds: 0.25 }),
            change(6, 0.5, { transitionStyle: 1 }),
        ],
        0,
    )
    // Generated by tests/timescale_reference.py in sonolus-next-sekai-engine,
    // using its independent Decimal oracle at 100 digits of precision.
    const cases = [
        [-5, -3, 3.5],
        [-3, -1, 4.305555555555555],
        [-3, 0, 6.314814814814815],
        [-3, 0.75, 6.422453703703703],
        [-1, 0, -0.5833333333333334],
        [0, 2, 250.5],
        [0, 2.5, 250.625],
        [0.75, 3, 180.1591796875],
        [2, 2.5, 5e-5],
        [2.5, 2, 0.75],
        [2, 3, 0.0001375],
        [3, 5.5, 0.4583333333333333],
        [4, 7, 2.5416666666666665],
        [-3, 7, 150.21604938271605],
        [7, -3, 2093.3333333333335],
        [0, -3, -11],
        [3, 0.75, 2005.25],
        [2, 0, -0.10020000000000001],
        [7, 4, -2.5416666666666665],
        [-5, 7, 177.94444444444446],
        [7, -5, 2135.3333333333335],
        [0, 0, 0],
        [2, 2, 0],
    ] as const
    for (const [now, target, expected] of cases) {
        close(noteDistance(group, now, target), expected)
    }
})

test('changes before the playback start still affect scaled time and hiding', () => {
    const group = createTimescaleGroup(
        [change(-4, 2, { skipSeconds: 0.5, hideNotes: true }), change(-2, 3, { skipSeconds: 1 })],
        0,
    )
    close(scaledTimeAt(group, -5), -5)
    close(scaledTimeAt(group, -4), -3.5)
    close(scaledTimeAt(group, -3), -1.5)
    close(scaledTimeAt(group, -2), 1.5)
    close(noteDistance(group, -3, -2), 3)
    assert.equal(hideNotesAt(group, -5), false)
    assert.equal(hideNotesAt(group, -4), true)
    assert.equal(hideNotesAt(group, -2), false)
})

test('applies all tied skips in order while the final marker controls visibility and speed', () => {
    const group = createTimescaleGroup(
        [change(1, 2, { skipSeconds: 2, hideNotes: true }), change(1, 3, { skipSeconds: -0.5 })],
        0,
    )
    close(scaledTimeAt(group, 1), 2.5)
    close(noteDistance(group, 0, 1), 2.5)
    close(noteDistance(group, 1, 2), 3)
    assert.equal(hideNotesAt(group, 1), false)
})

test('zero scroll speed uses the engine epsilon, while zero timescale stops time', () => {
    const scroll = createTimescaleGroup([change(0, 0, { transitionStyle: 1 })], 0)
    const timescale = createTimescaleGroup([change(0, 0)], 0)
    close(noteDistance(scroll, 1, 3), 0.0002)
    close(noteDistance(scroll, 3, 1), -0.0002)
    close(noteDistance(timescale, 1, 3), 0)
})

test('local distance keeps subsecond precision after a large earlier skip', () => {
    const group = createTimescaleGroup(
        [change(0, 1, { skipSeconds: 1e16 }), change(2, 2), change(4, 1)],
        0,
    )
    close(noteDistance(group, 1, 1.125), 0.125)
    close(noteDistance(group, 1, 5), 6)
    close(noteDistance(group, 5, 1), -6)
})

test('empty groups retain ordinary time and extreme distances use the engine limit', () => {
    const group = createTimescaleGroup([], 0)
    close(noteDistance(group, -4, 5), 9)
    close(noteDistance(group, 5, -4), -9)
    close(scaledTimeAt(group, -4), -4)
    assert.equal(hideNotesAt(group, 0), false)
    assert.equal(noteDistance(group, 0, 1e30), 1e20)
    assert.equal(noteDistance(group, 1e30, 0), -1e20)
})
